version: '3.9'
services: 
  test-db:
    image: postgres
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: test-db
    # volumes:
    #   - ./temp-db/items-db-data/:/var/lib/postgresql/data/
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U testuser -d itemsdb" ]
    #   interval: 10s
    #   timeout: 45s
    #   retries: 10